### ISSUE TITLE
Instantiation error when running mysql_async example

### ISSUE THREAD

**Issue by sunng87** [WasmEdge/wasmedge-db-examples#14]
I'm getting this error when running mysql_async example using `wasmedge target/...`. It has something to do with TLS as from the information.

```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `wasmedge target/wasm32-wasi/debug/crud.wasm`
[2023-11-14 02:55:33.510] [error] instantiation failed: unknown import, Code: 0x62
[2023-11-14 02:55:33.510] [error]     When linking module: "rustls_client" , function name: "new_codec"
[2023-11-14 02:55:33.510] [error]     At AST node: import description
[2023-11-14 02:55:33.510] [error]     At AST node: import section
[2023-11-14 02:55:33.510] [error]     At AST node: module
```

**Comment by juntao** [comment]
This example shows how to use a TLS connection to a remote MySQL database, so you will need to install WasmEdge with the TLS plugin like this:

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasmedge_rustls
```

Or, if you want to run LLM AI as well:

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml wasmedge_rustls
```

I will update the docs for this.

**Comment by juntao** [comment]
Sorry, the example demonstrate how to make a TLS connection to a remote database. You will need to install the WasmEdge TLS plugin to make it work.

Our installer still has an issue with the TLS plugin, but you can install by hand following the steps in the CI. 

https://github.com/WasmEdge/wasmedge-db-examples/blob/main/.github/workflows/examples.yml

Lines 77-84 install WasmEdge with the TLS plugin

Thanks.

**Comment by sunng87** [comment]
Thank you! I think we will need to update README for that.

**Comment by juntao** [comment]
Updated the README and the GitHub Action script. 

You can now install WasmEdge and the TLS plugin in a single line.
